### ISSUE TITLE
Component 'adminui-content-card-button-title' supports only one button in header

### ISSUE THREAD

**Issue by yudin-s** [RippleOSI/OS-TeleHealth#5]
Right now we can add only one button in header using regular Admin bundle UI that is placed in "col" class with handler. 

My suggesting is make assembly method that will accept object with buttonColour, buttonText, hooks and etc. named "putButton" and put button to the header. 

For manage this button can add getButton(id) or findButton() 

Also icons, handler events inside button can be changed by card lifetime so need method such as "replace"  or so.

**Comment by tony-shannon** [comment]
issue linked to this library
https://github.com/robtweed/wc-admin-ui

**Comment by robtweed** [comment]
This can be done manually, and there's an example in adminui-crud.js   See lines 198-307 which defines a new button assembly, and then lines 704 - 709 which adds it to the title (ie the adminui-content-card-button-title component)

**Comment by yudin-s** [comment]
Resolved by created new component www/components/ptwq/components/ptwq-content-card-multibutton-title.js

**Comment by yudin-s** [comment]
Resolved by creating  new component www/components/ptwq/components/ptwq-content-card-multibutton-title.js
