### ISSUE TITLE
Datatable CRUD Hooks margin loss

### ISSUE THREAD

**Issue by yudin-s** [RippleOSI/OS-TeleHealth#6]
After we are make any changes inside of DataTable in any CRUD view (patients, vitals, events and etc.) dataTable render results are places in wrong place by ready of incorrect loadGroup function activity. 

New DataTable instance with CRUD result must be sets inside "card-body" but after table is destroyed and created again it's placed on root element (adminui-content-card-body)

Video with explanation: https://www.loom.com/share/05ca29bdd4404d52ab9dcfd5abe2a52b

**Comment by robtweed** [comment]
This will be fixed in the next update.  In the meantime can you change:

    target

to

    target.rootElement

in the following lines of adminui-crud.js:

493, 549, 600

and config this fixes it please

Rob

**Comment by yudin-s** [comment]
Resolved
